#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(master|main|develop|dev|uat)$|(feature|release|hotfix)\/[a-z0-9._-]+$|^HEAD$"

message="there is something wrong with your branch name, branch names in this project must adhere to this contract: $valid_branch_regex. 
your commit will be rejected, you should rename your branch to a valid name and try again"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
