// Copyright 2024 Mackay Zhou <mackay.chow@gmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by goctl. DO NOT EDIT.

package group_contact

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupContactFieldNames          = builder.RawFieldNames(&GroupContact{})
	groupContactRows                = strings.Join(groupContactFieldNames, ",")
	groupContactRowsExpectAutoSet   = strings.Join(stringx.Remove(groupContactFieldNames, "`Id`"), ",")
	groupContactRowsWithPlaceHolder = strings.Join(stringx.Remove(groupContactFieldNames, "`Id`"), "=?,") + "=?"
)

type (
	groupContactModel interface {
		Insert(ctx context.Context, data *GroupContact) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*GroupContact, error)
		Update(ctx context.Context, data *GroupContact) error
		Delete(ctx context.Context, id int64) error
	}

	defaultGroupContactModel struct {
		conn  sqlx.SqlConn
		table string
	}

	GroupContact struct {
		Id             int64         `db:"Id"`
		GroupId        sql.NullInt64 `db:"GroupId"`        // 群ID
		UserId         sql.NullInt64 `db:"UserId"`         // 用户ID
		CategoryId     int64         `db:"CategoryId"`     // 用户自定义分组ID
		UserNickname   string        `db:"UserNickname"`   // 群昵称
		Remark         string        `db:"Remark"`         // 群备注
		Background     string        `db:"Background"`     // 背景
		IsDisturb      int64         `db:"IsDisturb"`      // 是否免打扰
		IsTop          int64         `db:"IsTop"`          // 是否置顶
		IsShowNickname int64         `db:"IsShowNickname"` // 是否显示群昵称
		ApprovalStatus int64         `db:"ApprovalStatus"` // 审批状态
		ApprovalAt     sql.NullTime  `db:"ApprovalAt"`     // 审批时间
		CreatedAt      sql.NullTime  `db:"CreatedAt"`      // 创建时间
		UpdatedAt      sql.NullTime  `db:"UpdatedAt"`      // 更新时间
	}
)

func newGroupContactModel(conn sqlx.SqlConn) *defaultGroupContactModel {
	return &defaultGroupContactModel{
		conn:  conn,
		table: "`GroupContact`",
	}
}

func (m *defaultGroupContactModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `Id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupContactModel) FindOne(ctx context.Context, id int64) (*GroupContact, error) {
	query := fmt.Sprintf("select %s from %s where `Id` = ? limit 1", groupContactRows, m.table)
	var resp GroupContact
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupContactModel) Insert(ctx context.Context, data *GroupContact) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, groupContactRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.CategoryId, data.UserNickname, data.Remark, data.Background, data.IsDisturb, data.IsTop, data.IsShowNickname, data.ApprovalStatus, data.ApprovalAt, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultGroupContactModel) Update(ctx context.Context, data *GroupContact) error {
	query := fmt.Sprintf("update %s set %s where `Id` = ?", m.table, groupContactRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.GroupId, data.UserId, data.CategoryId, data.UserNickname, data.Remark, data.Background, data.IsDisturb, data.IsTop, data.IsShowNickname, data.ApprovalStatus, data.ApprovalAt, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultGroupContactModel) tableName() string {
	return m.table
}
