// Code generated by goctl. DO NOT EDIT.
package types

type ContactAddReq struct {
	OwnerId int64  `json:"ownerId"`
	Mobile  string `json:"mobile"`
}

type FormIdReq struct {
	Id int64 `form:"id"`
}

type GroupCreateReq struct {
	Name     string `json:"name"`
	OwnerId  int64  `json:"ownerId"`
	Icon     string `json:"icon"`
	Category uint8  `json:"category"`
	Memo     string `json:"memo"`
}

type GroupJoinReq struct {
	UserId  int64  `json:"userId"`
	GroupId string `json:"groupId"`
}

type GroupResp struct {
	Id        int64  `json:"id"`
	GroupId   string `json:"groupId"`
	Name      string `json:"name"`
	OwnerId   int64  `json:"ownerId"`
	Icon      string `json:"icon"`
	Category  uint8  `json:"category"`
	Memo      string `json:"memo"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type PathIdReq struct {
	Id int64 `path:"id"`
}

type PathIdStrReq struct {
	Id string `path:"id"`
}

type UploadReq struct {
	File string `form:"file"`
}

type UploadResp struct {
	Url string `json:"url"`
}

type UserLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserRegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Sex      uint8  `json:"sex"`
}

type UserResp struct {
	Id          int64  `json:"id"`
	Mobile      string `json:"mobile"`
	Avatar      string `json:"avatar"`
	Sex         uint8  `json:"sex"`
	Nickname    string `json:"nickname"`
	Token       string `json:"token"`
	Memo        string `json:"memo"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
	LastLoginAt string `json:"lastLoginAt"`
}
