// Copyright 2024 Mackay Zhou <mackay.chow@gmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by goctl. DO NOT EDIT.

package user_contact

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userContactFieldNames          = builder.RawFieldNames(&UserContact{})
	userContactRows                = strings.Join(userContactFieldNames, ",")
	userContactRowsExpectAutoSet   = strings.Join(stringx.Remove(userContactFieldNames, "`Id`"), ",")
	userContactRowsWithPlaceHolder = strings.Join(stringx.Remove(userContactFieldNames, "`Id`"), "=?,") + "=?"
)

type (
	userContactModel interface {
		Insert(ctx context.Context, data *UserContact) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserContact, error)
		Update(ctx context.Context, data *UserContact) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserContactModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserContact struct {
		Id             int64        `db:"Id"`
		OwnerId        int64        `db:"OwnerId"`        // 所有者用户ID
		DstId          int64        `db:"DstId"`          // 目标用户ID
		CategoryId     int64        `db:"CategoryId"`     // 用户自定义分组ID
		Background     string       `db:"Background"`     // 背景
		IsDisturb      int64        `db:"IsDisturb"`      // 是否免打扰(0:否 1:是)
		IsTop          int64        `db:"IsTop"`          // 是否置顶(0:否 1:是)
		IsRemind       int64        `db:"IsRemind"`       // 是否提醒(0:否 1:是)
		IsInitiator    int64        `db:"IsInitiator"`    // 是否为发起方(0:否 1:是)
		ApprovalStatus int64        `db:"ApprovalStatus"` // 审批状态(0:待审批 10:已通过 20:已拒绝)
		ReApply        int64        `db:"ReApply"`        // 是否重新申请(0:否 1:是)
		ApprovalAt     sql.NullTime `db:"ApprovalAt"`     // 审批时间
		CreatedAt      sql.NullTime `db:"CreatedAt"`      // 创建时间
		UpdatedAt      sql.NullTime `db:"UpdatedAt"`      // 更新时间
	}
)

func newUserContactModel(conn sqlx.SqlConn) *defaultUserContactModel {
	return &defaultUserContactModel{
		conn:  conn,
		table: "`UserContact`",
	}
}

func (m *defaultUserContactModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `Id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserContactModel) FindOne(ctx context.Context, id int64) (*UserContact, error) {
	query := fmt.Sprintf("select %s from %s where `Id` = ? limit 1", userContactRows, m.table)
	var resp UserContact
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserContactModel) Insert(ctx context.Context, data *UserContact) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userContactRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OwnerId, data.DstId, data.CategoryId, data.Background, data.IsDisturb, data.IsTop, data.IsRemind, data.IsInitiator, data.ApprovalStatus, data.ReApply, data.ApprovalAt, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultUserContactModel) Update(ctx context.Context, data *UserContact) error {
	query := fmt.Sprintf("update %s set %s where `Id` = ?", m.table, userContactRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OwnerId, data.DstId, data.CategoryId, data.Background, data.IsDisturb, data.IsTop, data.IsRemind, data.IsInitiator, data.ApprovalStatus, data.ReApply, data.ApprovalAt, data.CreatedAt, data.UpdatedAt, data.Id)
	return err
}

func (m *defaultUserContactModel) tableName() string {
	return m.table
}
